---
title: "Final"
author: "Emily Mauch"
date: "4/18/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages to install, include=FALSE}
install.packages("naniar")
install.packages("igraph")
install.packages("ggraph")
```

```{r Packages to open, include=FALSE}
library(tidyverse)
library(rvest) 
library(naniar)
library(igraph)
```


```{r}
#Function : data
#Input : a url to a 50 of the top 1000 movies. Selects and formats movie rank, title, year, directors/actors, votes/gross
#Output : a data frame of 50 movies with variables above

data <- function(x){
  html <- read_html(x)
  top_50 <- html_nodes(html, ".sort-num_votes-visible , .text-muted+ p , .genre , .unbold , .lister-item-header a")
  a <- html_text(top_50) 
  b <- str_replace_all(a, "[\r\n]" , "")
  c <- str_replace_all(b, "[ ]+" , "")
  d <- gsub("[()]", "", c)   
  x <- str_replace_all(d, "[I]+", "")
  as.data.frame(matrix(x, ncol = 6, nrow = 50, byrow= TRUE))
}


a <- data("https://www.imdb.com/search/title/?groups=top_1000&start=1")
b <- data("https://www.imdb.com/search/title/?groups=top_1000&start=51&ref_=adv_nxt")
c <- data("https://www.imdb.com/search/title/?groups=top_1000&start=101&ref_=adv_nxt")
d <- data("https://www.imdb.com/search/title/?groups=top_1000&start=151&ref_=adv_nxt")
e <- data("https://www.imdb.com/search/title/?groups=top_1000&start=201&ref_=adv_nxt")
f <- data("https://www.imdb.com/search/title/?groups=top_1000&start=251&ref_=adv_nxt")
g <- data("https://www.imdb.com/search/title/?groups=top_1000&start=301&ref_=adv_nxt")
h <- data("https://www.imdb.com/search/title/?groups=top_1000&start=351&ref_=adv_nxt")
i <- data("https://www.imdb.com/search/title/?groups=top_1000&start=401&ref_=adv_nxt")
j <- data("https://www.imdb.com/search/title/?groups=top_1000&start=451&ref_=adv_nxt")
k <- data("https://www.imdb.com/search/title/?groups=top_1000&start=501&ref_=adv_nxt")
l <- data("https://www.imdb.com/search/title/?groups=top_1000&start=551&ref_=adv_nxt")
m <- data("https://www.imdb.com/search/title/?groups=top_1000&start=601&ref_=adv_nxt")
n <- data("https://www.imdb.com/search/title/?groups=top_1000&start=651&ref_=adv_nxt")
o <- data("https://www.imdb.com/search/title/?groups=top_1000&start=701&ref_=adv_nxt")
p <- data("https://www.imdb.com/search/title/?groups=top_1000&start=751&ref_=adv_nxt")
q <- data("https://www.imdb.com/search/title/?groups=top_1000&start=801&ref_=adv_nxt")
r <- data("https://www.imdb.com/search/title/?groups=top_1000&start=851&ref_=adv_nxt")
s <- data("https://www.imdb.com/search/title/?groups=top_1000&start=901&ref_=adv_nxt")
t <- data("https://www.imdb.com/search/title/?groups=top_1000&start=951&ref_=adv_nxt")

top <- rbind(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t)
```



```{r warning=FALSE}
#Formatting data frame 

top <- top %>% separate(V1, c("Rank", NA), sep="[.]") %>%
  separate(V4, c("Genre1", "Genre2", "Genre3"), sep="[,]")%>%
  separate(V5, c("Director", "Actor"), sep = "[|]") %>%
  separate(Director, c(NA, "Director"), sep = "[:]") %>%
  separate(Actor, c(NA, "Actors"), sep = "[:]")%>%
  separate(V6, c("Votes", "Gross"), sep = "[|]", extra="merge")  %>%
  separate(Votes, c(NA, "Votes"), sep = "[:]") %>% 
  rename("Title" = "V2", "Year"="V3") %>% 
  separate(Actors, c("Actor1", "Actor2", "Actor3", "Actor4"), sep = "[,]") %>%
  separate(Gross, c("Gross1", "Gross2"), sep="[:]") %>% 
  separate(Gross2, c("Gross2", "Gross3"), sep = "[|]") %>% 
  separate(Gross2, c("Gross2", "Gross4"), sep = "[#]") %>%
  select("Rank":"Votes", "Gross2")%>%
  rename("Gross" = "Gross2") %>%
  replace_with_na(replace = list(Gross = ""))
top_100 <- top %>% arrange(Year) %>% head(100)
```

```{r}
#Producing data frame "actors". Contains 3 rows per movie that correlates each actor in the movie to the "top" actor. Modified top for graphing 
#Format must be "Actor1", "Actor2" then "title"
top_longer <- top  %>% 
  select(Title, Actor1:Actor2)
col_order <- c("Actor1", "Actor2", "Title")
top_longer <- top_longer[, col_order]

#Producing Data frame "Actors" contains just actors and removes all duplicates. Needed for graphing function 
Actors <- top %>% 
  select(Actor1:Actor2, Title) %>%  
  pivot_longer(cols= "Actor1":"Actor2",names_to= "Remove", values_to = 'Actor') %>% 
  select(-"Remove")
#Removes duplicate actors
Actors <- distinct(Actors, Actor)
```


```{r}
#Producing actor network plot 
#Input:
  #d: data frame with top actor linked the 2nd, 3rd and 4th actors divided out by movie
  #vertices: Just a list of all of the actors in movies 
  #direct = FALSE due to multiple actors in multiple movies and aren't directed linked to every other actor 
#Output: list of actors and who they are related to 
actorNetwork <- graph_from_data_frame(d=top_longer, vertices=Actors, directed=FALSE)
plot(actorNetwork)
```


```{r}
#Idea 1 for graph
library(ggraph)
ggraph(actorNetwork)+
  geom_edge_link(alpha = 0.5) +     
  geom_node_point(size = 0.5, shape = 21, stroke = 1,
                  fill = 'white', color = 'black') +
  geom_node_text(aes(label=NA), size = 3) +
  theme_void()
```

```{r}
#Idea 2 for graph 
par(mar = c(0,0,0,0))
ll <- layout.auto(actorNetwork)

plot(actorNetwork, 
     layout=ll,
     vertex.label= NA,
     vertex.size=5)
```

```{r}
#Shiny App with all actors 

server <- function(input, output, session) {
   # global variable, what type of plot interaction
    interaction_type <- "click"
    # observe for user interaction and change the global interaction_type variable
    observeEvent(input$user_click, interaction_type <<- "click")
    observeEvent(input$user_brush, interaction_type <<- "brush")
#Plot     
    output$plot <- renderPlot({
         par(mar = c(0,0,0,0))
          ll <- layout.auto(actorNetwork) 
          
          plot(actorNetwork, 
               layout=ll,
               vertex.label= NA,
               vertex.size=5)
    })
# generate the data to put in the table
    dat <- reactive({
        
        user_brush <- input$user_brush
        user_click <- input$user_click
        
        if(interaction_type == "brush") res <- brushedPoints(Actors, user_brush)
        if(interaction_type == "click") res <- nearPoints(Actors, user_click, threshold = 10, maxpoints = 1)
        
        return(res)
        
    })
#Making data table    
    output$table <- DT::renderDataTable(DT::datatable(dat()[,c("Actor")]))
    
}

#ui <- fluidPage(
#output you actually see    
  #  h3("Top 2 Actors from top 1000 movies"),
    #plotOutput("plot", click = "user_click", brush = "user_brush"),
    #DT::dataTableOutput("table")
    
#)

#shinyApp(ui = ui, server = server)
```


```{r}
#par(mar = c(0,0,0,0))
#ll <- layout.auto(actorNetwork_50)

#plot(actorNetwork_50, 
     #layout=ll,
     #vertex.label= NA,
     #vertex.size=5)
```


```{r}
#Below is only 50 of the movies - test to find people with only once connection 

top_50 <- top_longer[1:50,]

Actors_50 <- top_50 %>% 
  pivot_longer(cols= "Actor1":"Actor2",names_to= "Remove", values_to = 'Actor') %>% 
  select(-"Remove")
col_order2 <- c("Actor", "Title")
Actors_50 <- Actors_50[, col_order2]
Actors_50 <-  distinct(Actors_50, Actor)


actorNetwork_50 <- graph_from_data_frame(d=top_50, vertices=Actors_50, directed=FALSE)
```


```{r}
output <- c()
```


```{r}
server <- function(input, output, session) {
   # global variable, what type of plot interaction
    interaction_type <- "click"
    # observe for user interaction and change the global interaction_type variable
    observeEvent(input$user_click, interaction_type <<- "click")
    observeEvent(input$plot1_dblclick, {
          brush <- input$plot1_brush
            if (!is.null(brush)) {
            ranges$x <- c(brush$xmin, brush$xmax)
            ranges$y <- c(brush$ymin, brush$ymax)

           } else {
          ranges$x <- NULL
          ranges$y <- NULL
    }
  })
    ranges <- reactiveValues(x = NULL, y = NULL)
    
    output$plot <- renderPlot({
         par(mar = c(0,0,0,0))
          ll <- layout.auto(actorNetwork) 
          
          plot(actorNetwork, 
               layout=ll,
               vertex.label= NA,
               vertex.size=5)
          coord_cartesian(xlim = ranges$x, ylim = ranges$y, expand = FALSE)
    })
    # generate the data to put in the table
    dat <- reactive({
        
        user_click <- input$user_click
        

        if(interaction_type == "click") res <- nearPoints(Actors, user_click, threshold = 10, maxpoints = 1)
        
        return(res)
        
    })
    
    output$table <- DT::renderDataTable(DT::datatable(dat()[,c("Actor")]))
    
}

ui <- fluidPage(
    
    h3("Top 2 Actors from top 1000 movies"),
    plotOutput("plot", click = "user_click", 
               dblclick = "plot1_dblclick",
                brush = brushOpts(id = "plot1_brush",
                    resetOnNew = TRUE)),
    DT::dataTableOutput("table")
    
)

shinyApp(ui = ui, server = server)
```
```{r}
##possibly extra example 

#install.packages("visNetwork")
#install.packages('DT')
library(tidyverse)
library(igraph)                    
library(visNetwork)            
library(DT)
library(plotly)

###getting data files 
hp_links <- read_csv("relations.csv")
hp_nodes <- read_csv("characters.csv")

##creating network
hp_network <- graph_from_data_frame(hp_links,
                                    vertices= hp_nodes,
                                    directed = F)
hp_network %>% 
  edge_density()


hp_network %>% 
  distances() %>% 
  as.vector() %>%              
  as_tibble() %>%              
  plot_ly(x = ~value) %>% 
  add_histogram()

hp_network %>% 
  get_diameter() %>% 
  length()

hp_nodes <- hp_nodes %>%
  mutate(label = name) %>% 
  mutate(title = name) %>% 
  mutate(degree= degree(hp_network)) %>% 
  mutate(value = degree)

hp_links <- hp_links %>% 
  mutate(betweenness= edge_betweenness(hp_network)) %>% 
  mutate(value= betweenness)



edges <- data.frame(from = hp_links$source, to=hp_links$target)


View(hp_nodes)
View(hp_links)

visNetwork(nodes=hp_nodes, edges, main = "Harry Potter Network Diagram") %>% 
  visIgraphLayout(layout = "layout_nicely") %>% 
  visOptions(highlightNearest = T, nodesIdSelection = T)


```

```{r}

Actors <- top %>% 
  select(Actor1:Actor2, Title) %>%  
  pivot_longer(cols= "Actor1":"Actor2",names_to= "Remove", values_to = 'Actor') %>% 
  select(-"Remove")

View(Actors)
actorswide <- top %>% 
  select(Actor1:Actor2)

distinctactors <- top %>% 
  select(Actor1:Actor2) %>%  
  pivot_longer(cols= "Actor1":"Actor2",names_to= "Remove", values_to = 'Actor') %>%    select(-"Remove")
#Removes duplicate actors
distinctactors <- distinct(distinctactors, Actor)



distinctactors$ID <- seq(1:1304)
distinctactors$Actor2 <- distinctactors$Actor
colnames(distinctactors) <- c("Actor1", "ID", "Actor2")
View(distinctactors)
merged1 <- merge(distinctactors, actorswide, by="Actor1")
mergedint <-merged1[,-3]
colnames(mergedint) <- c("Actor1", "ID", "Actor2")
mergedint2 <- merge(distinctactors, mergedint, by="Actor2")

finalmerged <- select(mergedint2, -c(1,2,4))
colnames(finalmerged) <- c("Source", "Target")
View(finalmerged)
hugenodes <- select(distinctactors, c(1,2))
colnames(hugenodes) <- c("Actor", "ID")
View(hugenodes)



huge_links <- finalmerged
huge_nodes <- hugenodes

##creating network
huge_network <- graph_from_data_frame(hp_links,
                                    vertices= hp_nodes,
                                    directed = F)
hp_network %>%   
  edge_density() 


hp_network %>% 
  distances() %>% 
  as.vector() %>%              
  as_tibble() %>%              
  plot_ly(x = ~value) %>% 
  add_histogram()

hp_network %>% 
  get_diameter() %>% 
  length()

hp_nodes <- hp_nodes %>%
  mutate(label = name) %>% 
  mutate(title = name) %>% 
  mutate(degree= degree(hp_network)) %>% 
  mutate(value = degree)

hp_links <- hp_links %>% 
  mutate(betweenness= edge_betweenness(hp_network)) %>% 
  mutate(value= betweenness)



edges <- data.frame(from = hp_links$source, to=hp_links$target)


View(hp_nodes)
View(hp_links)

visNetwork(nodes=hp_nodes, edges, main = "Harry Potter Network Diagram") %>% 
  visIgraphLayout(layout = "layout_nicely") %>% 
  visOptions(highlightNearest = T, nodesIdSelection = T)

```
```{r}
actorswide2 <- data.frame(actorswide)
unique_actors1 <- data_frame("actor1" = unique(actorswide2$Actor1)) 
unique_actors1 <- unique_actors1 %>% arrange(actor1)
unique_actors1$connections <- table(actorswide2$Actor1)
unique_actors2 <- data_frame("actor1" = unique(actorswide2$Actor2)) 
unique_actors2 <- unique_actors2 %>% arrange(actor1)
unique_actors2$connections <- table(actorswide2$Actor2)
unique_1<- rbind(anti_join(unique_actors1, unique_actors2, "actor1"), anti_join(unique_actors2, unique_actors1, "actor1")) 
unique_1 <- unique_1 %>% filter(connections == "1")
actorswide2$tf <- actorswide2$Actor1 %in% unique_1$actor1
actorswide2$tf2 <- actorswide2$Actor2 %in% unique_1$actor1
actorswide2 <- actorswide2 %>% filter(tf == TRUE & tf2 == TRUE)
```

>>>>>>> bc394c71cecc088718dbaa99ad1dfaa312412ebd
